#+PROPERTY: header-args :comments org :tangle .gitconfig

* Aliases

  #+BEGIN_SRC sh
  [alias]
  #+END_SRC

** Diff

   Basic configuration:
   - ignore all white space, even when whitespaces were added where no whitespace before.
   - show a word diff.
   - detect file rename with 75% similarity threshold.
   #+BEGIN_SRC sh
     d = diff --ignore-all-space --color-words --find-renames=75
     dt = difftool
     dc = show --ignore-all-space --color-words --find-renames=75
     dtc = "!diffCommit() { git dt "$1~" "$1"; }; diffCommit"
     dch = "!git dc HEAD"
     dth = "!git dtc HEAD"
   #+END_SRC

   Diff between staging > working:
   #+BEGIN_SRC sh
           dsw = "!git d"
   #+END_SRC

   Diff between HEAD > working:
   #+BEGIN_SRC sh
           dhw = "!git d HEAD"
   #+END_SRC

   Diff between HEAD > staging:
   #+BEGIN_SRC sh
           dhs = "!git d --cached"
   #+END_SRC

   Diffs including submodules:
   #+BEGIN_SRC sh
           dsm = "!git d; git submodule foreach 'git d'"
           dsmsw = "!git dsw; git submodule foreach 'git dsw'"
           dsmhs = "!git dhs; git submodule foreach 'git dhs'"
           dsmhw = "!git dhw; git submodule foreach 'git dhw'"
   #+END_SRC

** Logs

   Basic format:
   - abbreviated commit hash :: %h yellow.
   - ref names :: %d green.
   - subject :: %s white.
   - author date, relative :: %ar magenta.
   - author name :: %an blue.
   #+BEGIN_SRC sh
           log-format = log --format=format:"%C(yellow)%h%C(bold\\ green)%d%C(reset)\\ %s\\ %C(magenta)%ar\\ %C(blue)%an"
   #+END_SRC

   Basic graph log:
   #+BEGIN_SRC sh
           l = "!git log-format --graph"
   #+END_SRC

   Log all refs:
   #+BEGIN_SRC sh
           la = "!git l --all"
   #+END_SRC

   With diffstat:
   #+BEGIN_SRC sh
           ll = "!git la --stat"
   #+END_SRC

   Log my commits:
   - author :: author name pattern filter

   #+BEGIN_SRC sh
           lam = "!git la --author=Auclair"
           llm = "!git ll --author=Auclair"
   #+END_SRC

   Log only HEAD:
   #+BEGIN_SRC sh
           lh = "!git log-format -n 1"
           llh = "!git lh --stat"
   #+END_SRC

   Order by author date:
   #+BEGIN_SRC sh
           ld = "!git l --author-date-order"
           lad = "!git ld --all"
   #+END_SRC

   Log one file's history:
   #+BEGIN_SRC sh
           lf = "!git la --follow"
   #+END_SRC

   Find commit introducing/removing string (regexp):
   - pickaxe-regex :: consider argument is a regex;
   #+BEGIN_SRC sh
           li = "!logintro() { git log-format -S$1 --pickaxe-regex; }; logintro"
   #+END_SRC

   Find commit with diff containing a string (regexp):
   #+BEGIN_SRC sh
           lm = "!logmod() { git log-format -G$1; }; logmod"
   #+END_SRC

** Stash

   Stash only working:
   - --patch :: chunked stash, implies =--keep-index=
   #+BEGIN_SRC sh
           st = stash save --patch
           stw = "!git st"
   #+END_SRC

   Stash staging + working:
    -we need to reset =--keep-index= flag implied by =--patch= option
   #+BEGIN_SRC sh
           stsw = "!git st --no-keep-index"
   #+END_SRC

   Apply & pop, restoring index:
   #+BEGIN_SRC sh
           sta = stash apply --index
           stp = stash pop --index
   #+END_SRC

   Inspect stashes:
   #+BEGIN_SRC sh
           sts = stash show
   #+END_SRC

   Inspect stashes diff:
   #+BEGIN_SRC sh
           stdiff = stash show --patch
   #+END_SRC

** Commit

   Shortcuts for lazy people:
   - --patch :: chunked add
   - -v :: add diff to message draft for inspection
   - --amend :: add modifications to previous commit
   - --no-edit :: use previous commit message without change
   #+BEGIN_SRC sh
           ap = add --patch
           c = commit -v
           ca = "!git c --amend"
           oops = "!git ca --no-edit"
   #+END_SRC

   Unstage changes:
   - --patch :: chunked unstage
   #+BEGIN_SRC sh
           us = reset HEAD
           usi = reset --patch HEAD
   #+END_SRC

   Add file deletions:
   #+BEGIN_SRC sh
           addrm = "!git rm $(git ls-files --deleted)"
   #+END_SRC

** Merges

   Shorcuts for lazy people:
   #+BEGIN_SRC sh
           mt = mergetool
   #+END_SRC

   Prefer no-fast-forward merges:
   #+BEGIN_SRC sh
           m = merge --no-ff
   #+END_SRC

   Explicit fast-forward:
   #+BEGIN_SRC sh
           ff = merge --no-commit
   #+END_SRC

   Fix another commit:
   #+BEGIN_SRC sh
           fix = "!fixcommit() { git commit --fixup=$1; }; fixcommit"
   #+END_SRC

   Squash : perform a merge but do not create a merge commit.
   Allows to get the modifications from another branch, like a merge, but without actually performing the merge.
   #+BEGIN_SRC sh
           ms = merge --squash
   #+END_SRC

** Reset

   Reset HEAD / Keep changes in staging + working:
   #+BEGIN_SRC sh
           rh = reset --soft
   #+END_SRC

   Reset HEAD + staging / Keep changes in working / Update working with <commit>:
   #+BEGIN_SRC sh
           rhs = reset --merge
   #+END_SRC

   Reset HEAD + staging + working:
   #+BEGIN_SRC sh
           ra = reset --hard
   #+END_SRC

** Cleanup

   Discard changes in working / Keep untracked:
   - --patch :: chunked discard
   #+BEGIN_SRC sh
           discard = checkout --
           dis = "!git discard"
           disi = checkout --patch --
   #+END_SRC

   Clean untracked:
   - remove untracked directories (-d).
   #+BEGIN_SRC sh
           cl = clean -d -f
   #+END_SRC

   Clean untracked + ignored:
   - remove untracked directories (-d).
   - remove ignored files (-x).
   #+BEGIN_SRC sh
           purge = clean -x -d -f
   #+END_SRC

** Branches

   Shortcuts for lazy people:
   #+BEGIN_SRC sh
           b = branch
           bd = branch -d
   #+END_SRC

   Show the current branch name:
   - --short :: show shorten branch name (=refs/heads/master -> master=)
   #+BEGIN_SRC sh
           bh = symbolic-ref --short HEAD
   #+END_SRC

   List all local branches:
   - -v :: show branches commit
   - -vv :: show the differences between local/remote branches
   #+BEGIN_SRC sh
           bl = "!git f && git branch -vv"
   #+END_SRC

   List all branches, including remotes:
   - --all : show all local/remote branches
   #+BEGIN_SRC sh
           ba = "!git bl --all"
   #+END_SRC

   Create branch on <commit>:
   #+BEGIN_SRC sh
           bc = checkout -b
   #+END_SRC

** Rebase

   Shortcuts for leazy people:
   #+BEGIN_SRC sh
           rbc = "!git rebase --continue"
           rba = "!git rebase --abort"
   #+END_SRC

   Rebase:
   - --interactive :: interactive by default
   #+BEGIN_SRC sh
           rb = rebase --interactive
   #+END_SRC

   Rebase on updated origin/master:
   #+BEGIN_SRC sh
           rbm = "!git fetch && git rb origin/master"
           rbfm = "!git fetch && git rb origin/refonte-master"
   #+END_SRC

   Rebase exec:
   - --exec <cmd> :: run a command after each rebased commit
   #+BEGIN_SRC sh
           rbx = "!git rb --exec"
   #+END_SRC

** Files

   Grep <pattern> in tracked files:
   - ignore binary files :: -I.
   - empty line between different files :: --break.
   #+BEGIN_SRC sh
           g = grep -I --break
   #+END_SRC

   Grep all working, also untracked files:
   #+BEGIN_SRC sh
           gw = "!git g --untracked"
   #+END_SRC

   Grep staging:
   #+BEGIN_SRC sh
           gs = "!git g --cached"
   #+END_SRC

** Remote

   Shortcuts for lazy people:
   #+BEGIN_SRC sh
     p = push
     oopf = "!git oops && git pf"
   #+END_SRC

   Clone:
   - always checkout submodules.
   #+BEGIN_SRC sh
           clone = clone --recursive
   #+END_SRC

   Basic fetch:
   - remote tags.
   - remove remote-tracking branches that do not exists on remote.
   #+BEGIN_SRC sh
           f = fetch --prune --tags
   #+END_SRC

   Synchronize tags with remote:
   #+BEGIN_SRC sh
           ft = fetch -p origin +refs/tags/*:refs/tags/*
   #+END_SRC

   Push force, respects new changes in remote:
   #+BEGIN_SRC sh
           pf = push --force-with-lease
   #+END_SRC

   Set remote-tracking branch:
   #+BEGIN_SRC sh
           pup = push --set-upstream
           pub = "!git pup origin `git bh`"
   #+END_SRC

   Check that new commits in submodules have been pushed to their remote:
   #+BEGIN_SRC sh
           purc= push --recurse-submodules=check
   #+END_SRC

   Push new commits in submodules when necessary:
   #+BEGIN_SRC sh
           purd= push --recurse-submodules=on-demand
   #+END_SRC

** Submodules

   Shortcuts for lazy people:
   #+BEGIN_SRC sh
           sms = submodule status
   #+END_SRC

   Show commits between last registered commit (HEAD) in super project, and current commit (Working) in submodule:
   #+BEGIN_SRC sh
           smhw = submodule summary
   #+END_SRC

   Show commits between last registered commit (HEAD) in super project, and commit staged (Staging) for submodule:
   #+BEGIN_SRC sh
           smhs = submodule summary --cached -- HEAD
   #+END_SRC

   Show commits between commit staged (Staging) in super project, and current commit (Working) in submodule:
   #+BEGIN_SRC sh
           smsw = submodule summary --files
   #+END_SRC

   Execute a command in each submodule, continue on fail.
   #+BEGIN_SRC sh
           smf = "!foreach() { git submodule foreach \"$1 || true\"; }; foreach"
   #+END_SRC

   Update submodules to commits registered in HEAD of super project:
   #+BEGIN_SRC sh
           smu = submodule update
   #+END_SRC

   Update modules to last commit of remote-tracked branch defined in .gitmodules:
   #+BEGIN_SRC sh
           smur = submodule update --remote
   #+END_SRC

** Miscellaneous

   Shortcuts for lazy people:
   #+BEGIN_SRC sh
           s = status
           co = checkout
   #+END_SRC

   List all aliases:
   #+BEGIN_SRC sh
           lal = "!git config -l | grep alias | cut -c 7-"
   #+END_SRC

   Search an alias:
   #+BEGIN_SRC sh
           sal = "!search_alias() { git lal | grep -i --color \"$1\"; }; search_alias"
   #+END_SRC

   Display last tag name in <commit> history:
   #+BEGIN_SRC sh
           lasttag = describe --tags --abbrev=0
   #+END_SRC

   Toggle ignore local modification on <path>:
   #+BEGIN_SRC sh
           changed = update-index --no-assume-unchanged
           unchanged = update-index --assume-unchanged
   #+END_SRC

   Retry a Git command every 2s until it succeeds:
   #+BEGIN_SRC sh
           bourrin = "!retry() { until $(git $1); do sleep 2; echo "Retrying"; date; done; }; retry"
   #+END_SRC

   Retrieve standard ignore files for a language:
   #+BEGIN_SRC sh
           ignore = "!gi() { curl -L -s https://www.gitignore.io/api/$@ ;}; gi"
   #+END_SRC

   Get/Set the project's git-hooks directory:
   #+BEGIN_SRC sh
           hooks = config core.hooksPath
   #+END_SRC

* User Info

  #+BEGIN_SRC sh
  [user]
          name = Auclair Emmanuel
          email = auclair.emmanuel@gmail.com
  #+END_SRC

* Pretty diff

  Pretty diff pager:
  - =npm install -g diff-so-fancy=
  - one tab = 2 spaces.
  - raw control chars :: -R.
  - quit if one screen :: -F.
  - no init :: -X.
  #+BEGIN_SRC sh
    [pager]
            diff = diff-so-fancy | less --tabs=2 -RFX
            difftool = true
            show = diff-so-fancy | less --tabs=2 -RFX
    [interactive]
            diffFilter = "less --tabs=2 -RFX"
  #+END_SRC

  - show submodules commit logs in super projet diffs.
  - use =icdiff= as a diff tool for side-by-side comparison.
  #+BEGIN_SRC sh
  [diff]
          submodule = log
          tool = difftastic
  [difftool]
          prompt = false
  [difftool "difftastic"]
          cmd = difft "$MERGED" "$LOCAL" "$REMOTE"
  [difftool "icdiff"]
          cmd = icdiff --line-numbers $LOCAL $REMOTE
  #+END_SRC

* Colors

  #+BEGIN_SRC sh
  [color]
          ui = true
  [color "diff"]
          meta = "yellow bold"
          commit = "green bold"
          frag = "magenta bold"
          old = "red bold"
          new = "green bold"
          whitespace = "red reverse"
  [color "diff-highlight"]
          oldNormal = "red bold"
          oldHighlight = "red bold 52"
          newNormal = "green bold"
          newHighlight = "green bold 22"
  [color "branch"]
          current = "green reverse"
          local = green
          remote = yellow
  [color "status"]
          added = green
          changed = red
          untracked = cyan
          unmerged = magenta
  #+END_SRC

* Miscellaneous

  Grep:
  - display lines numbers in results
  #+BEGIN_SRC sh
  [grep]
          lineNumber = true
  #+END_SRC

  Push:
  - push to origin/upstream, or <other>/<current>
  #+BEGIN_SRC sh
  [push]
          default = simple
  #+END_SRC

  Blame:
  - display relative dates
  #+BEGIN_SRC sh
  [blame]
          date = relative
  #+END_SRC

  Help:
  - auto correct git command and execute after 1x 0.1s
  #+BEGIN_SRC sh
  [help]
          autocorrect = 1
  #+END_SRC

  Interactive:
  - don't need to type enter after single-key shortcuts in interactive commands.
  #+BEGIN_SRC sh
  [interactive]
          singleKey = true
  #+END_SRC

  Rebase:
  - auto stash local modifs before/after rebase
  - auto fix/squash commit with message starting with =!fixup= or =!squash=
  #+BEGIN_SRC sh
  [rebase]
          autostash = true
          autosquash = true
          missingCommitsCheck = ignore
  #+END_SRC

  Credentials
  - remember credentials in local store
  #+BEGIN_SRC sh
  [credential]
          helper = store
  #+END_SRC

  Merge:
  - use =kdiff3= as mergetool
  - do not keep =.orig= backup files after successful merge
  #+BEGIN_SRC sh
  [merge]
          tool = kdiff3
          conflictstyle = diff3
  [mergetool]
          keepBackup = false
  #+END_SRC

  Remember conflicts resolutions
  #+BEGIN_SRC sh
  [rerere]
          enabled = true
  #+END_SRC
