(define-key input-decode-map [?\C-m] [C-m])

(global-set-key "\C-z"            'advertised-undo)
(global-set-key "\C-l"            'goto-line)
(global-set-key (kbd "<RET>")     'newline-and-indent)
(global-set-key (kbd "<C-prior>") 'previous-buffer)
(global-set-key (kbd "<C-next>")  'next-buffer)
(global-set-key (kbd "<S-SPC>")   'just-one-space)
(global-set-key (kbd "<M-left>")  'back-to-indentation)
(global-set-key (kbd "<C-m>")     'kmacro-call-macro)

;; (progn
;;   ;; define a prefix keymap
;;   (define-prefix-command 'my-modes-key-map)
;;   (define-key my-modes-key-map (kbd "a") 'eauc/align-array))
;; (global-set-key (kbd "C-e")      my-modes-key-map)

(global-set-key (kbd "<f1>")    'find-file)
(global-set-key (kbd "<f2>")    'save-buffer)
(global-set-key (kbd "<C-f2>")  'write-file)
(global-set-key (kbd "<f3>")    'other-window)
(global-set-key (kbd "<C-f3>")  'buffer-menu-other-window)
(global-set-key (kbd "<S-f3>")  'ido-switch-buffer)
(global-set-key (kbd "<f4>")    'comment-or-uncomment-region)
(global-set-key (kbd "<C-f4>")  'eauc/indent-buffer)
(global-set-key (kbd "<f5>")    'bookmark-set)
(global-set-key (kbd "<C-f5>")  'bookmark-jump)
(global-set-key (kbd "<f6>")    'pop-to-mark-command)
(global-set-key (kbd "<C-f6>")  'pop-global-mark)
(global-set-key (kbd "<f10>")   'kill-this-buffer)
(global-set-key (kbd "<C-f10>") 'save-buffers-kill-terminal)
