(use-package lispy
  :ensure t
  :bind (:map lispy-mode-map
              ("M-[" . lispy-backward)
              ("M-]" . lispy-forward)
              (")" . self-insert-command)
              ("[" . self-insert-command)
              ("]" . self-insert-command)
              (";" . self-insert-command)
              ("DEL" . backward-delete-char-untabify)
              ("M-DEL" . lispy-delete-backward))
  :init
  (add-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode 1)))
  (add-hook 'clojure-mode-hook (lambda () (lispy-mode 1)))
  (add-hook 'clojurescript-mode-hook (lambda () (lispy-mode 1)))
  (cheatsheet-add-group 'Lispy
                        '(:key "p" :description "Eval (other window)")
                        '(:key "E" :description "Eval and insert")
                        '(:key "e" :description "Eval sexp")
                        '(:key "C-2" :description "Arglist inline")
                        '(:key "C-1" :description "Describe inline")
                        '(:key "M-k" :description "Kill sentence")
                        '(:key "M-d" :description "Kill word")
                        '(:key "C-," :description "Kill at point")
                        '(:key "xu" :description "Unbind")
                        '(:key "xl" :description "Defun to lambda")
                        '(:key "xi" :description "Conds to ifs")
                        '(:key "xd" :description "Lambda to defun")
                        '(:key "xc" :description "Ifs to cond")
                        '(:key "xb" :description "Bind")
                        '(:key "C" :description "Convolute")
                        '(:key "R" :description "Raise following sexp (replace parent with sexp and followin siblings)")
                        '(:key "r" :description "Raise sexp (replace parent with sexp)")
                        '(:key "O" :description "Oneline")
                        '(:key "M" :description "Multiline")
                        '(:key "S" :description "Transform sexp into string")
                        '(:key "/" :description "Splice into parent")
                        '(:key "<" :description "Barf")
                        '(:key ">" :description "Slurp")
                        '(:key "t" :description "Teleport sexp")
                        '(:key "w" :description "Move sexp up")
                        '(:key "s" :description "Move sexp down")
                        '(:key "M-DEL" :description "Delete sexp backward")
                        '(:key "c" :description "Clone sexp below")
                        '(:key "n" :description "Copy sexp")
                        '(:key "M-m" :description "Mark symbol")
                        '(:key "m" :description "Mark sexp")
                        '(:key "i" :description "Indent")
                        '(:key "M-," :description "Jump back")
                        '(:key "F" :description "Follow : jump to first/marked symbol")
                        '(:key "M-." :description "Jump to symbol")
                        '(:key "g" :description "Jump to tag in current directory")
                        '(:key "G" :description "Jump to tag in current file")
                        '(:key "Q" :description "Jump to char in sexp")
                        '(:key "q" :description "Jump to paren")
                        '(:key "d" :description "Switch to other side of sexp")
                        '(:key "A" :description "Beginning of defun")
                        '(:key "M-]" :description "End of sexp")
                        '(:key "M-[" :description "Beginning of sexp")
                        '(:key "b" :description "Back history")
                        '(:key "f" :description "Flow")
                        '(:key "l" :description "Right")
                        '(:key "h" :description "Left")
                        '(:key "j" :description "Down")
                        '(:key "k" :description "Up")))
