(use-package smartparens
  :ensure t
  :bind (("s-<left>" . sp-backward-sexp)
         ("s-<right>" . sp-forward-sexp)
         ("M-<up>" . sp-up-sexp)
         ("s-<down>" . sp-down-sexp)
         ("s-<up>" . sp-backward-up-sexp)
         ("M-<down>" . sp-backward-down-sexp)
         ("M-s-<left>" . sp-beginning-of-sexp)
         ("M-s-<right>" . sp-end-of-sexp)
         ("s-b" . sp-backward-symbol)
         ("s-f" . sp-forward-symbol)
         ("s-[" . sp-backward-unwrap-sexp)
         ("s-]" . sp-unwrap-sexp)
         ("C-s-[" . sp-backward-slurp-sexp)
         ("C-s-]" . sp-forward-slurp-sexp)
         ("M-s-[" . sp-backward-barf-sexp)
         ("M-s-]" . sp-forward-barf-sexp)
         ("s-t" . sp-transpose-sexp)
         ("s-k" . sp-kill-sexp)
         ("s-<backspace>" . sp-backward-kill-sexp))
  :init
  (add-hook 'lisp-mode-hook #'smartparens-mode)
  (add-hook 'lisp-interaction-mode-hook #'smartparens-mode)
  (add-hook 'emacs-lisp-mode-hook #'smartparens-mode)
  (add-hook 'clojure-mode-hook #'smartparens-mode)
  (add-hook 'cider-repl-mode-hook #'smartparens-mode)
  (add-hook 'scheme-mode-hook #'enable-smartparens-mode)
  (add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
  (add-hook 'lisp-interaction-mode-hook 'turn-on-eldoc-mode)
  )

(use-package smartparens-config
  :ensure smartparens)
