vim.keymap.set({ 'n', 'x', 'o' }, '[', '<Plug>(sexp_flow_to_next_open)', { desc = 'move to next open bracket' })
vim.keymap.set({ 'n', 'x', 'o' }, '{', '<Plug>(sexp_flow_to_prev_open)', { desc = 'move to prev open bracket' })
vim.keymap.set({ 'n', 'x', 'o' }, ']', '<Plug>(sexp_flow_to_next_close)', { desc = 'move to next close bracket' })
vim.keymap.set({ 'n', 'x', 'o' }, '}', '<Plug>(sexp_flow_to_prev_close)', { desc = 'move to prev close bracket' })

vim.keymap.set({ 'n', 'x', 'o' }, 'B', '<Plug>(sexp_flow_to_prev_leaf_head)', { desc = 'move to prev element head' })
vim.keymap.set({ 'n', 'x', 'o' }, 'W', '<Plug>(sexp_flow_to_next_leaf_head)', { desc = 'move to next element head' })
vim.keymap.set({ 'n', 'x', 'o' }, 'F', '<Plug>(sexp_flow_to_prev_leaf_tail)', { desc = 'move to prev element tail' })
vim.keymap.set({ 'n', 'x', 'o' }, 'E', '<Plug>(sexp_flow_to_next_leaf_tail)', { desc = 'move to next element tail' })

vim.keymap.set({ 'x', 'o' }, 'af', '<Plug>(sexp_outer_list)', { desc = 'outer list' })
vim.keymap.set({ 'x', 'o' }, 'if', '<Plug>(sexp_inner_list)', { desc = 'inner list' })
vim.keymap.set({ 'x', 'o' }, 'aF', '<Plug>(sexp_outer_top_list)', { desc = 'outer top list' })
vim.keymap.set({ 'x', 'o' }, 'iF', '<Plug>(sexp_inner_top_list)', { desc = 'inner top list' })
vim.keymap.set({ 'x', 'o' }, 'ae', '<Plug>(sexp_outer_element)', { desc = 'outer element' })
vim.keymap.set({ 'x', 'o' }, 'ie', '<Plug>(sexp_inner_element)', { desc = 'inner element' })
vim.keymap.set({ 'x', 'o' }, 'as', '<Plug>(sexp_outer_string)', { desc = 'outer string' })
vim.keymap.set({ 'x', 'o' }, 'is', '<Plug>(sexp_inner_string)', { desc = 'inner string' })

vim.keymap.set('n', '>I', '<Plug>(sexp_insert_at_list_tail)', { desc = 'insert at list tail' })
vim.keymap.set('n', '<I', '<Plug>(sexp_insert_at_list_head)', { desc = 'insert at list head' })
vim.keymap.set('n', '>f', '<Plug>(sexp_swap_list_forward)', { desc = 'move list forward' })
vim.keymap.set('n', '<f', '<Plug>(sexp_swap_list_backward)', { desc = 'move list backward' })
vim.keymap.set('n', '>e', '<Plug>(sexp_swap_element_forward)', { desc = 'move element forward' })
vim.keymap.set('n', '<e', '<Plug>(sexp_swap_element_backward)', { desc = 'move element backward' })
vim.keymap.set('n', '>)', '<Plug>(sexp_emit_tail_element)', { desc = 'barf tail element' })
vim.keymap.set('n', '>(', '<Plug>(sexp_capture_prev_element)', { desc = 'slurp head element' })
vim.keymap.set('n', '<(', '<Plug>(sexp_emit_head_element)', { desc = 'barf head element' })
vim.keymap.set('n', '<)', '<Plug>(sexp_capture_next_element)', { desc = 'slurp tail element' })
vim.keymap.set('n', '<leader>@', '<Plug>(sexp_splice_list)', { desc = 'splice list' })
vim.keymap.set('n', '<leader>o', '<Plug>(sexp_raise_list)', { desc = 'raise list' })
vim.keymap.set('n', '<leader>O', '<Plug>(sexp_raise_element)', { desc = 'raise element' })
vim.keymap.set('n', '<leader>?', '<Plug>(sexp_convolute)', { desc = 'convolute list' })
